name: Deploy Solidarity App to ECS

on:
  push:
    branches:
      - main  # 仅当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # 使用 Node.js 22

      # 安装 cnpm（淘宝镜像加速工具）
      - name: Install cnpm
        run: npm install -g cnpm

      # 清理 npm 缓存
      - name: Clean npm cache
        run: npm cache clean --force

      # 安装依赖并构建应用
      - name: Install dependencies and build
        run: |
          cnpm i
          npm run build

      # 压缩构建文件
      - name: Archive build files
        run: zip -r solidarity-app.zip . -x node_modules/\* .git/\*

      # 创建 Git 标签（基于日期）
      - name: Create Git Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      # 将文件上传到服务器
      - name: Deploy to ECS server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          password: ${{ secrets.ECS_PASSWORD }}
          source: solidarity-app.zip
          target: /var/www/solidarity/

      # 在服务器上解压并启动服务
      - name: Execute remote commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.ECS_HOST }}
          username: ${{ secrets.ECS_USER }}
          password: ${{ secrets.ECS_PASSWORD }}
          script: |
            cd /var/www/solidarity
            unzip -o solidarity-app.zip
            npm install --production
            pm2 restart solidarity || pm2 start npm --name "solidarity" -- start
            
      # 创建 GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
